# -*- coding: utf-8 -*-
"""Quiz_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeyAUHkB02VYkwbrRQ2xw3zn2UyaqlKa
"""

# PART A : Python Fundamentals &  Logic Building
# section A1 : Control Structures  &  Logic building

# 1. Tcket class Validation
ticket_class = "Sleeper"
if ticket_class == "Economy":
    print("Fare type: Budget-friendly with basic amenities.")
elif ticket_class == "Business":
    print("Fare type: Premium with enhanced comfort and services.")
elif ticket_class == "Sleeper":
    print("Fare type: Comfortable overnight travel with sleeping arrangements.")
else:
    print("Invalid ticket class. Please choose Economy, Business, or Sleeper.")

# 2. Age-Based Concession
age =62
if age >= 60:
    print("Eligible for senior citizen concession. You get a discount on your fare.")
else:
    print("Not eligible for senior citizen concession.")

# 3. Seat Availability Check
available_seats = 0
if available_seats > 0:
    print("Confirm Ticket")
elif available_seats == 0:
    print("Waiting List")
else:
    print("Tarkal only")

# 4. Trian Delay Compensation
delay_hours = 5
if delay_hours > 4:
    print("Eligible for compensation. You can claim a refund for the delay.")
else:
    print("Not eligible for compensation.")
if delay_hours > 3:
    print("Train delayed! Please check the updated schedule.")
    print("Eligible for compensation. You can claim a refund for the delay.")
    print("Eligible for compensation. You can claim a refund for the delay.")
else:
    print("Train on time. No compensation applicable.")

# 5.Platform allocation Logic
platform_number = 0
if platform_number <= 0:
    print("Error: Invalid platform number. Please check the platform assignment.")
else:
    print(f"Platform number {platform_number} assigned successfully.")

# Section A2:  Loops & Iterations

# 6. Passengers Boarding list
passengers =["Amit","Neha","Ravi","Sara"]
for passenger in passengers:
    print(f"Boarding confirmed for passenger: {passenger}")

# 7. Coach number Display
total_coaches = 12

# Task :
# Print Coach numbers using loop
for coach_number in range(1, total_coaches + 1):
    seat_number = coach_number * 10  # Assuming 10 seats per coach
    print(f"Coach Number: {coach_number}")
    print(f"Seat Assigned: {seat_number}")

# 8. Reminder before departure

count = 0
while count < 3:
    print("Reminder: Departure will commence soon. Please be ready.")
    count += 1

# 9. Skip Cancelled stations
stations =["Delhi","Cancelled","Kanpur","Lucknow"]

for station in stations:
    if station == "Cancelled":
        continue
    print(f"Next station: {station}")

# 10. Emergency Stop

events =["Normal","Normal","Emergency","Normal"]
for event in events:
    if event == "Emergency":
        print("Emergency detected! Stopping operations.")
        break
    print(f"Event status: {event}")

# Section A3:  Built-in data structures

# 11. Reservation List (List)
reservations = ["PNR001", "PNR002"]
reservations.append("PNR003")
print(f"Reservations after adding: {reservations}")
reservations.remove("PNR001")
print(f"Reservations after removing: {reservations}")
print(f"Total reservations: {len(reservations)}")

# 12. Unique Routes (Set)
routes = ["Delhi-Mumbai", "Delhi-Mumbai", "Delhi-Goa"]
unique_routes = set(routes)
print(f"Unique routes: {unique_routes}")

# 13. Train  Details (Tuple)
train = ("Rajdhani", 12301, "Delhi-Mumbai")
try:
    train[1] = 12302
except TypeError as e:
    print(f"Error: {e}. Tuples are immutable and cannot be modified.")
    print(f"Train Details: Name - {train[0]}, Number - {train[1]}, Route - {train[2]}")

# 14. Passenger Profile (Dictionary
profile = {"name": "Ankit", "age": 30, "coach": "B2"}
profile["coach"] = "A1"
for key, value in profile.items():
    print(f"{key}: {value}")

# 15. Highest fareRoute

fares = {"Delhi-Mumbai": 1500, "Delhi-Goa": 2100}
highest_fare_route = max(fares, key=fares.get)
print(f"Highest fare route: {highest_fare_route} with fare {fares[highest_fare_route]}")

# Section A4 : Functions & Comprehensions
# 16. Journey Time calculator

def calculate_journey_time(distance, speed):
    if speed <= 0:
        return "Speed must be greater than zero."
    time = distance / speed
    return time

# 17. Fare Calculator

def calculate_fare(distance, train_class):
    base_fare = 500  # Base fare for distance
    if train_class == "AC":
        base_fare *= 2  # AC class is twice the base fare
    return base_fare * distance

# 18. Lambda : tax Calculation

calculate_gst = lambda fare: fare * 0.05

# 19.filter Confirmed Tickets

tickets = ["CONFIRMED", "WAITING", "CONFIRMED"]
confirmed_tickets = [ticket for ticket in tickets if ticket == "CONFIRMED"]
print(f"Confirmed tickets: {confirmed_tickets}")

# 20.Route Mapping
routes =[ "Delhi-Mumbai", "Delhi-Goa"]
route_distances = {route: (1500 if route == "Delhi-Mumbai" else 2100) for route in routes}
print(f"Route distances: {route_distances}")

# Section A5:  OOP , Files & Exceptions

# 21 Train Class

class Train:
    def __init__(self, name, number):
        self.name = name
        self.number = number

    def display_info(self):
        print(f"Train Name: {self.name}, Train Number: {self.number}")
train1 = Train("Rajdhani", 12301)
train1.display_info()

# 22. Inheritance : Express Train

class ExpressTrain(Train):
    def __init__(self, name, number, speed):
        super().__init__(name, number)
        self.speed = speed

    def display_speed(self):
        print(f"Express Train Speed: {self.speed} km/h")
express_train = ExpressTrain("Shatabdi", 12001, 150)
express_train.display_info()
express_train.display_speed()

# 23.Encapsulation :

class Ticket:
    def __init__(self, fare):
        self.__fare = fare  # Private attribute

    def get_fare(self):
        return self.__fare
ticket = Ticket(1500)
print(f"Ticket Fare: {ticket.get_fare()}")

# 24.File Handling : Booking records

booking_details = "PNR001, Delhi-Mumbai, Confirmed\nPNR002, Delhi-Goa, Waiting"
with open("bookings.txt", "w") as file:
    file.write(booking_details)
with open("bookings.txt", "r") as file:
    content = file.read()
    print("Booking Details from file:")
    print(content)

# 25. Exception Handling :

try:
    ticket_number = int(input("Enter your ticket number: "))
    print(f"Your ticket number is {ticket_number}.")
except ValueError:
    print("Invalid input! Please enter a valid ticket number.")

# PART B : Libraries , Analytics  & EDA

# Section B1: Numpy

# 26. Daily Passenger Count
import numpy as np

daily_passengers = np.array([1200, 1500, 1100, 1600, 1700, 1300, 1400])
max_passengers = np.max(daily_passengers)
min_passengers = np.min(daily_passengers)
avg_passengers = np.mean(daily_passengers)
print(f"Max Passengers: {max_passengers}, Min Passengers: {min_passengers}, Avg Passengers: {avg_passengers}")

# 27. Fare Adjustment

fares = np.array([1500, 2000, 2500, 3000])
adjusted_fares = fares * 1.10
print(f"Adjusted Fares: {adjusted_fares}")

# 28. Seat matrix

seat_matrix = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])
print("Seat Matrix:")
print(seat_matrix)

# 29.Peak Hour Analysis

hourly_passengers = np.array([100, 200, 300, 400, 500, 600, 700, 800])
peak_hour_index = np.argmax(hourly_passengers)
print(f"Peak Passenger Hour Index: {peak_hour_index}, Passengers: {hourly_passengers[peak_hour_index]}")

# 30. Distance Normalization

route_distances = np.array([1500, 2100, 1800, 2400])
normalized_distances = (route_distances - np.min(route_distances)) / (np.max(route_distances) - np.min(route_distances))
print(f"Normalized Distances: {normalized_distances}")

# Section B2: Pandas
import pandas as pd

#  31.Railway Dataset Creation
data = {
    "Train": ["Rajdhani", "Shatabdi", "Garib Rath"],
    "Route": ["Delhi-Mumbai", "Delhi-Chennai", "Delhi-Kolkata"],
    "Fare": [1500, 1200, 800],
    "Passengers": [200, 250, 300]
}
df = pd.DataFrame(data)
print("Railway Dataset:")
print(df)

# 32. Revenue Per Train

df["Revenue"] = df["Fare"] * df["Passengers"]
print("Railway Dataset with Revenue:")
print(df)
average_revenue = df["Revenue"].mean()
high_earning_trains = df[df["Revenue"] > average_revenue]
print("High Earning Trains:")
print(high_earning_trains)

# 33. Filter High Revenue Routes
average_fare = df["Fare"].mean()
high_revenue_routes = df[df["Fare"] > average_fare]
print("High Revenue Routes:")
print(high_revenue_routes)

# 34. Missing Data Handling
df_with_missing = df.copy()
df_with_missing.loc[1, "Fare"] = None  # Introduce missing value
df_with_missing["Fare"].fillna(df_with_missing["Fare"].mean(), inplace=True)
print("DataFrame after handling missing Fare values:")
print(df_with_missing)

# 35.GroupBy Analysis
grouped_data = df.groupby("Route")["Fare"].mean().reset_index()
print("Mean Fare per Route:")
print(grouped_data)

# section B3 : Matplotlib
import matplotlib.pyplot as plt

#36. Passenger trend line
days = [1, 2, 3, 4, 5, 6, 7]
passenger_counts = [1200, 1500, 1100, 1600, 1700, 1300, 1400]
plt.plot(days, passenger_counts, marker='o')
plt.title("Passenger Count Over Days")
plt.xlabel("Days")
plt.ylabel("Passenger Count")
plt.grid()
plt.show()

#37. Route Revenue Bar Chart

routes = ["Delhi-Mumbai", "Delhi-Chennai", "Delhi-Kolkata"]
revenues = [300000, 250000, 240000]
plt.bar(routes, revenues, color='purple')
plt.title("Revenue per Route")
plt.xlabel("Routes")
plt.ylabel("Revenue")
plt.show()

#38. Fare Distribution

fares = [1500, 1200, 800, 2000, 1800, 2200, 1600, 1400, 1700]
plt.hist(fares, bins=5, color='lightblue', edgecolor='black')
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Number of Routes")
plt.show()

# 39.Train Occupancy Pie Chart

train_types = ["Express", "Local", "Freight"]
occupancy = [60, 30, 10]
plt.pie(occupancy, labels=train_types, autopct='%1.1f%%', startangle=140)
plt.title("Train Occupancy Percentage")
plt.show()

# 40 Delay Analysis Plot

delays = [0, 1, 2, 3, 4, 5]
num_trains = [50, 40, 30, 20, 10, 5]
plt.scatter(delays, num_trains, color='green')
plt.title("Delay Analysis")
plt.xlabel("Delay (hours)")
plt.ylabel("Number of Trains")
plt.show()

